trigger: 
 - main

pool:
   vmImage: 'ubuntu-latest'
variables:
  GO_CACHE_DIR: $(Pipeline.Workspace)/.cache/go-build/

steps:
- task: GoTool@0
  inputs:
    version: '1.19'
  displayName: 'Download Go'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Download dependencies'
- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Run tests'
- task: CmdLine@2
  inputs:
    script: 'mkdir build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o ./build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Build executable'

- task: CopyFiles@2
  inputs:
    SourceFolder:  '$(System.DefaultWorkingDirectory)/build'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy artifacts'

- task: PublishBuildArtifacts@1
  inputs:
     artifactName: oceniaczka
  displayName: 'Publish artifacts'
