trigger: 
 - main

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: Download Go@0
  inputs:
    version: '1.19'
- task: Download dependencies@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Run tests@0
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Build executable@0
  inputs:
    command: 'build ./build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Copy executable@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop